### ISSUE TITLE
dotnet 5

### ISSUE THREAD

**Issue by hhgm** [emoacht/ManagedNativeWifi#26]
Hi,

I am trying to use the library to get info about wifi running on a raspberry pi (linix), but I get this exception

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load shared library 'Wlanapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libWlanapi.dll: cannot open shared object file: No such file or directory
   at ManagedNativeWifi.Win32.NativeMethod.WlanOpenHandle(UInt32 dwClientVersion, IntPtr pReserved, UInt32& pdwNegotiatedVersion, SafeClientHandle& phClientHandle)
   at ManagedNativeWifi.Win32.BaseMethod.WlanClient..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at ManagedNativeWifi.Common.DisposableContainer`1..ctor(T content)
   at ManagedNativeWifi.NativeWifi.EnumerateAvailableNetworks(WlanClient client)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at SatelliteClient.Helpers.NetworkHelper.AvailableWiFiNetworks(OSType osType) in C:\Users\hhgm\source\Workspaces\TM nextGen 3.1\IoTClient\SatelliteClient\Helpers\NetworkHelper.cs:line 166

So seems like there is a library needed when you enumerate the collection on Linux that is missing.

Does this mean that it is not fully dotnet 5 compliant.. or just does not work on Linux?

**Comment by emoacht** [comment]
As explained in readme, this library calls Native Wifi Win32 APIs and so I don't think it works on other than Windows.

**Comment by hhgm** [comment]
I reckoned .  Do you know of any library for Linux?

tor. 21. apr. 2022 17.48 skrev emoacht ***@***.***>:
